/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DashboardAppIdRouteImport } from './routes/dashboard/$appId'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LoginSignUpRouteImport } from './routes/_login/sign-up'
import { Route as LoginSignInRouteImport } from './routes/_login/sign-in'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/_landing/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAppIdRoute = DashboardAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSignUpRoute = LoginSignUpRouteImport.update({
  id: '/_login/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSignInRoute = LoginSignInRouteImport.update({
  id: '/_login/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in': typeof LoginSignInRoute
  '/sign-up': typeof LoginSignUpRoute
  '/api/search': typeof ApiSearchRoute
  '/dashboard/$appId': typeof DashboardAppIdRoute
  '/docs/$': typeof DocsSplatRoute
  '/': typeof LandingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof LoginSignInRoute
  '/sign-up': typeof LoginSignUpRoute
  '/api/search': typeof ApiSearchRoute
  '/dashboard/$appId': typeof DashboardAppIdRoute
  '/docs/$': typeof DocsSplatRoute
  '/': typeof LandingIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_login/sign-in': typeof LoginSignInRoute
  '/_login/sign-up': typeof LoginSignUpRoute
  '/api/search': typeof ApiSearchRoute
  '/dashboard/$appId': typeof DashboardAppIdRoute
  '/docs/$': typeof DocsSplatRoute
  '/_landing/': typeof LandingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/api/search'
    | '/dashboard/$appId'
    | '/docs/$'
    | '/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/api/search'
    | '/dashboard/$appId'
    | '/docs/$'
    | '/'
    | '/dashboard'
  id:
    | '__root__'
    | '/dashboard'
    | '/_login/sign-in'
    | '/_login/sign-up'
    | '/api/search'
    | '/dashboard/$appId'
    | '/docs/$'
    | '/_landing/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginSignInRoute: typeof LoginSignInRoute
  LoginSignUpRoute: typeof LoginSignUpRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$appId': {
      id: '/dashboard/$appId'
      path: '/$appId'
      fullPath: '/dashboard/$appId'
      preLoaderRoute: typeof DashboardAppIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login/sign-up': {
      id: '/_login/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof LoginSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login/sign-in': {
      id: '/_login/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof LoginSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAppIdRoute: typeof DashboardAppIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAppIdRoute: DashboardAppIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginSignInRoute: LoginSignInRoute,
  LoginSignUpRoute: LoginSignUpRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  LandingIndexRoute: LandingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
