name: Publish

on:
  push:
    branches: [main]
    paths:
      - packages/core/package.json
      - packages/react/package.json
      - packages/solid-js/package.json

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.11"
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: bun install --frozen-lockfile
      - run: bun run --bun --filter './packages/*' build
      - run: bun run --bun check
      - name: Publish @simple-presence/core
        working-directory: packages/core
        run: npm publish core.tgz --provenance --access public
      - name: Publish @simple-presence/react
        working-directory: packages/react
        run: npm publish react.tgz --provenance --access public
      - name: Publish @simple-presence/solid-js
        working-directory: packages/solid-js
        run: npm publish solid-js.tgz --provenance --access public
